version: "3.7"

services:
  database:
    image: postgres
    container_name: parking-control-db
    restart: always
    ports:
      - 3007:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=parking-control-db
    volumes:
      - pg_data:/data/postgres
    networks:
      - database

volumes:
  pg_data:
    driver: local
networks:
  database:
    external: true